apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-access-binding
subjects:
- kind: User
  name: <YOUR_DEV_TEAM_USERNAME>
roleRef:
  kind: Role
  name: limited-access
  apiGroup: rbac.authorization.k8s.io